# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: 1loc_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none

pr: none

pool:
  vmImage: 'windows-latest'

jobs:
  - job: Job_1
    displayName: Agent job 1
    pool:
      vmImage: windows-latest
    steps:
      - checkout: self
      - task: cesve.one-loc-build.one-loc-build.OneLocBuild@2
        displayName: "Localization Build: localize/LocProject.json"
        inputs:
          locProj: "localize/LocProject.json"
          isCreatePrSelected: true
          repoType: gitHub
          gitHubPatVariable: "$(GitHubPat)"
          packageSourceAuth: patAuth
          patVariable: "$(OneLocBuildPat)"
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: drop"
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
